### ISSUE TITLE
Missing `$HELM_PLUGIN_DIR/untt` when updating to version 0.1.2

### ISSUE THREAD

**Issue by ryakad** [lrills/helm-unittest#33]
Updated to v0.1.2 and the plugin is now failing when trying to run unit tests saying that `$HELM_PLUGIN_DIR/untt` does not exist.

**Comment by lrills** [comment]
Hi, @ryakad. That may caused by some error when executing install hook, would you remove the plugin with `helm plugin remove unittest` then install again and see what happen?

**Comment by sjammy6** [comment]
@lrills It did not work for me too

**Comment by walkafwalka** [comment]
Hey @ryakad and @sjammy6, I am trying to revive this project since the maintainer seems to be gone. I also tried contacting him separately, but no response. If he comes back, I plan to submit any changes I make on my back to this one.

With more details, it is difficult to troubleshoot your issue, but perhaps you will have more luck with the forked release by running `helm plugin remove unittest` and then `helm plugin install https://gitlab.com/walkafwalka/helm-unittest`. Take a look at my fork here:
https://gitlab.com/walkafwalka/helm-unittest

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
