### ISSUE TITLE
Add sha256sum for release file

### ISSUE THREAD

**Issue by jjmartres** [lrills/helm-unittest#60]
Please provide SHA256 checksums for your releases

**Comment by walkafwalka** [comment]
Hey @jjmartres, I am trying to revive this project since the maintainer seems to be gone. I also tried contacting him separately, but no response. If he comes back, I plan to submit any changes I make on my back to this one.

For your particular request, I added checksums with this MR [here](https://gitlab.com/walkafwalka/helm-unittest/merge_requests/1) and release of [0.2.0](https://gitlab.com/walkafwalka/helm-unittest/releases).

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
