### ISSUE TITLE
Forking this project due to inactive maintainer

### ISSUE THREAD

**Issue by walkafwalka** [lrills/helm-unittest#64]
It seems the maintainer is inactive so I forked the repository to GitLab: https://gitlab.com/walkafwalka/helm-unittest. If the maintainer ever comes back within a reasonable time, I plan to merge my changes back to this one.

I have already fixed all of the current PRs in this project and have gone through the issues and fixed some of the easier ones. If you are still interested in seeing new features or fixing bugs, please post them over there so that I do not have to continue referencing the issues in this project.

The plan is to release 0.2 which is going to be focused on addressing a lot of the current bugs. I will then start releasing actual features in possibly 0.3 or the same release depending on how large the features are.

**Comment by lrills** [comment]
Hi @walkafwalka, just informed about this issue, sorry that I have buried myself in anothrer js project for last 8 months (Yah, I know it's just an excuse for unprofessional). I would have some DevOps work and plan to be full-time on open-sourced for the next while, so I would be able to pick up the matainer job again. And such the absence without announce thing would not happen again, I assure.

And about the future of this plugin, I take an open attitude if community or somone really enthusiastic in it would like to take over. To me, it would best to merge into helm repo as a standard plugin somehow, since it really needs such a feature.

Please give me any kind of thought you have about it if you like, thanks a lot!

**Comment by walkafwalka** [comment]
Hey @lrills, sorry if I stepped on any toes, I just love the work you have already done so much that I wanted to continue it. In fact, I submitted a feature suggestion at [helm/helm#5424] to have it integrated into the official Helm repo. As the maintainer of this repository, maybe it would help if you hopped in?

I have made a couple of changes to address some of the minor requests users have had. Also, I started addressing some of the lint errors that Helm would require to be fixed if they actually permitted a feature submission.

I will start submitting some PRs over the next couple of days/weeks of the work I have done. Thanks for coming back! :D

**Comment by lrills** [comment]
> Hey @lrills, sorry if I stepped on any toes, ...

Not at all! It's nice to know someone do care about it, I should come back earlier though :P. And it will be really good to be added into helm core, it will also fix the helm version supporting issue.

I will sum up bugs reported and new features these days, and I think it would be better to have 0.2.x based on your changes! Looking forward to your PRs :D

**Comment by gliptak** [comment]
@walkafwalka was https://gitlab.com/walkafwalka/helm-unittest set to private? Gitlab seems to require to login to view

**Comment by walkafwalka** [comment]
@gliptak I closed it since @lrills came back.
