### ISSUE TITLE
support variables

### ISSUE THREAD

**Issue by davidkarlsen** [lrills/helm-unittest#92]
The workaround described in https://github.com/helm/helm/issues/1311 is not supported in helm-unittest, you will get:
```
parse error in "fscronjob/templates/cronjob.yaml": template: fscronjob/templates/cronjob.yaml:70: undefined variable "$root"
```

for a block like:
```
{{- $root = . }}
{{- range $key, $value := .Values.configmap }}
- name: config
  mountPath: {{ $root.Values.config.mountPath }}/{{ $key }}
  subPath: {{ $key }}
  readOnly: true
{{- end }}
```

**Comment by davidkarlsen** [comment]
Never mind - error on my side (missing : in the assignment)

**Comment by amirschw** [comment]
Just FWI, you can use the `$` variable instead of defining the "root" variable:

`However, there is one variable that is always global - $ - this variable will always point to the root context. This can be very useful when you are looping in a range and need to know the chart’s release name.`

source: https://helm.sh/docs/chart_template_guide/#variables
